[dedication]
== Copyright Notice
Copyright © 2021 TmaxSoft Co., Ltd. All Rights Reserved. +
대한민국 경기도 성남시 분당구 황새울로258번길 29, BS 타워 9층 우)13595
 

**Website** +
http://www.tmaxsoft.co.kr +
기술서비스센터 +
Tel : +82-1544-8629 +
E-Mail : info@tmax.co.kr +

**Restricted Rights Legend ** +
All TmaxSoft Software(JEUS®) and documents are protected by copyright laws and international convention. +
TmaxSoft software and documents are made available under the terms of the TmaxSoft License Agreement and this document may only be distributed or copied in accordance with the terms of this agreement. No part of this document may be transmitted, copied, deployed, or reproduced in any form or by any means, electronic, mechan
ical, or optical, without the prior written consent of TmaxSoft Co., Ltd. Nothing in this software document and agreement constitutes a transfer of intellectual property rights regardless of whether or not such rights are registered)
or any rights to TmaxSoft trademarks, logos, or any other brand features. +
This document is for information purposes only. The company assumes no direct or indirect responsibilities for the contents of this document, and does not guarantee that the information contained in this document satisfies certain legal or commercial conditions. The information contained in this document is subject to change without prior notice due to product upgrades or updates. The company assumes no liability for any errors in this document.

이 소프트웨어(JEUS®) 사용설명서의 내용과 프로그램은 저작권법과 국제 조약에 의해서 보호받고 있습니다.  +
사용설명서의 내용과 여기에 설명된 프로그램은 TmaxSoft Co., Ltd.와의 사용권 계약 하에서만 사용이 가능하며, 사용설명서는 사용권 계약의 범위 내에서만 배포 또는 복제할 수 있습니다. 이 사용설명서의 전부 또는 일부분을TmaxSoft의 사전 서면 동의 없이 전자, 기계, 녹음 등의 수단을 사용하여 전송, 복제, 배포, 2차적 저작물작성 등의
행위를 하여서는 안 됩니다. 이 소프트웨어 사용설명서와 프로그램의 사용권 계약은 어떠한 경우에도 사용설명서 및 프로그램과 관련된 지적 재산권(등록 여부를 불문)을 양도하는 것으로 해석되지 아니하며, 브랜드나 로고, 상표 등을 사용할 권한을 부여하
지 않습니다. +
사용설명서는 오로지 정보의 제공만을 목적으로 하고, 이로 인한 계약상의 직접적 또는 간접적 책임을 지지 아니하며, 사용설명서 상의 내용은 법적 또는 상업적인 특정한 조건을 만족시키는 것을 보장하지는 않습니다. 사용설명서의 내용은 제품의 업그레이드나 수정에 따라 그 내용이 예고 없이 변경될 수 있으며, 내용상의 오
류가 없음을 보장하지 아니합니다.

**Trademarks** +
JEUS® is registered trademark of TmaxSoft Co., Ltd. +
JEUS®는 TmaxSoft Co., Ltd.의 등록 상표입니다. +
Java and Solaris are registered trademarks of Oracle Corporation and its subsidiaries and affiliates. +
Java, Solaris는 Oracle Corporation 및 그 자회사, 관계회사의 등록 상표입니다. +
Microsoft, Windows, and Windows NT are registered trademarks or trademarks of Microsoft Corporation. +
Microsoft, Windows, Windows NT는 Microsoft Corporation의 등록 상표 또는 상표입니다. +
HP-UX is a registered trademark of Hewlett Packard Enterprise Company. +
HP-UX는 Hewlett Packard Enterprise Company의 등록 상표입니다. +
AIX is a registered trademark of International Business Machines Corporation. +
AIX는 International Business Machines Corporation의 등록 상표입니다. +
UNIX is a registered trademark of X/Open Company, Ltd. +
UNIX는 X/Open Company, Ltd.의 등록 상표입니다. +
Linux is a registered trademark of Linus Torvalds. +
Linux는 Linus Torvalds의 등록 상표입니다. +
Noto is a trademark of Google Inc. Noto fonts are open source. All Noto fonts are published under the SIL Open Font License, Version 1.1. (https://www.google.com/get/noto/) +
Noto는 Google Inc.의 상표입니다. Noto 글꼴은 오픈 소스입니다. 모든 Noto 글꼴은 SIL Open Font License, 버전 1.1에 따라 게시됩니다. (https://www.google.com/get/noto/)
Other products and company names are trademarks or registered trademarks of their respective owners. +
기타 모든 제품들과 회사 이름은 각각 해당 소유주의 상호, 상표, 또는 등록 상표입니다. +
The names of companies, systems, and products mentioned in this manual may not necessarily be indicated with
a trademark symbol (TM, ®). +
본 사용설명서에 기재된 회사, 시스템, 제품 이름 등에 반드시 상표 표시 (TM, ®)를 하지는 않습니다. +

**Open Source Software Notice**  +
Some modules or files of this product are subject to the terms of the following licenses. : APACHE2.0, CDDL1.0,
EDL1.0, OPEN SYMPHONY SOFTWARE1.1, TRILEAD-SSH2, Bouncy Castle, BSD, MIT, SIL OPEN FONT1.1
Detailed Information related to the license can be found in the following directory : ${INSTALL_PATH}/lib/licenses +
본 제품의 일부 파일 또는 모듈은 다음의 라이선스를 준수합니다. : APACHE2.0, CDDL1.0, EDL1.0, OPEN SYM
PHONY SOFTWARE1.1, TRILEAD-SSH2, Bouncy Castle, BSD, MIT, SIL OPEN FONT1.1 +
관련 상세한 정보는 제품의 다음의 디렉터리에 기재된 사항을 참고해 주십시오. : ${INSTALL_PATH}/lib/licenses +

**안내서 정보**  +
안내서 제목: JEUS 소개 +
발행일: 2021-06-30 +
소프트웨어 버전: JEUS 21 +
안내서 버전: v2.1.1 +

